#!/usr/bin/env python
"""Regenerate the GGML regression-test fixtures.

Two artefacts:

  fixtures/regression_input.f32
      32000 raw little-endian float32: 16000 mic samples then 16000 ref
      samples. Matches the seed used by pytorch/tests/test_checkpoints.py
      so the same input flows through both regression suites.

  fixtures/<gguf_basename>.out.f32
      16000 raw little-endian float32: the model's output on the input
      above. Generated by running the test_regression binary in --save
      mode.

Usage:
    python tests/regenerate_fixtures.py --gguf <path-to-gguf> \\
        [--test-bin <path-to-built-test_regression>]

If --test-bin is omitted, we look in build/bin/test_regression and
build-cpu/bin/test_regression. Build it first with cmake.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
FIXTURES = HERE / "fixtures"

# Mirrors pytorch/tests/test_checkpoints.py — keep in lockstep.
_INPUT_SEED = 20260510
_INPUT_LEN = 16000


def _generate_input(out_path: Path):
    try:
        import torch
    except ImportError:
        sys.exit(
            "PyTorch is required to regenerate the input fixture. "
            "Install with: pip install torch"
        )
    g = torch.Generator().manual_seed(_INPUT_SEED)
    mic = torch.randn(1, _INPUT_LEN, generator=g).contiguous().view(-1)
    ref = torch.randn(1, _INPUT_LEN, generator=g).contiguous().view(-1)
    buf = torch.cat([mic, ref]).to(torch.float32).cpu().numpy()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    buf.tofile(out_path)
    print(f"[ok] wrote {out_path} ({buf.size} float32, {out_path.stat().st_size} bytes)")


def _find_test_binary(repo_root: Path) -> Path | None:
    for rel in ("build/bin/test_regression", "build-cpu/bin/test_regression"):
        p = repo_root / rel
        if p.exists():
            return p
    return None


def _generate_output(test_bin: Path, gguf_path: Path, input_path: Path, out_path: Path):
    cmd = [
        str(test_bin),
        "--gguf", str(gguf_path),
        "--gguf-name", gguf_path.name,
        "--input", str(input_path),
        "--save", str(out_path),
    ]
    print("$", " ".join(cmd))
    env = os.environ.copy()
    # Ensure libggml-cpu-*.so next to the binary is found.
    env["LD_LIBRARY_PATH"] = str(test_bin.parent) + ":" + env.get("LD_LIBRARY_PATH", "")
    subprocess.run(cmd, check=True, env=env)
    print(f"[ok] wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--gguf", type=Path, required=True, help="Path to the .gguf file")
    parser.add_argument("--test-bin", type=Path, default=None,
                        help="Path to the built test_regression binary")
    args = parser.parse_args()

    if not args.gguf.exists():
        sys.exit(f"GGUF not found: {args.gguf}")

    repo_root = HERE.parent.parent  # tests/ → ggml/ → repo
    test_bin = args.test_bin or _find_test_binary(repo_root / "ggml")
    if not test_bin or not test_bin.exists():
        sys.exit(
            "test_regression binary not found. Build it first:\n"
            "  cmake -B ggml/build -S ggml && cmake --build ggml/build -j --target test_regression\n"
            "or pass --test-bin <path>."
        )

    input_path = FIXTURES / "regression_input.f32"
    output_path = FIXTURES / f"{args.gguf.stem}.out.f32"

    _generate_input(input_path)
    _generate_output(test_bin, args.gguf, input_path, output_path)


if __name__ == "__main__":
    main()
