"""Per-checkpoint regression tests — load published weights and check
the forward output hasn't drifted.

Each manifest entry references a `.pt` file (looked up under
`$LOCALVQE_CKPT_DIR` or `pytorch/checkpoints/`) and a committed
reference output tensor. If the `.pt` isn't on disk the test SKIPS
rather than fails, so CI without HF access still runs the
architecture tests.

Reference outputs are generated by `tests/regenerate_fixtures.py`
using `_DETERMINISTIC_INPUT` below — never hand-edit them, regenerate.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import pytest
import torch
import yaml

from localvqe.model import LocalVQE


# Pinned input for every checkpoint. Bumping this seed is a breaking
# change — it invalidates every reference output in the fixtures dir.
_INPUT_SEED = 20260510
_INPUT_LEN = 16000  # 1 s @ 16 kHz, enough for the model's lookahead


def _deterministic_input(device="cpu"):
    g = torch.Generator(device=device).manual_seed(_INPUT_SEED)
    mic = torch.randn(1, _INPUT_LEN, generator=g, device=device)
    ref = torch.randn(1, _INPUT_LEN, generator=g, device=device)
    return mic, ref


def _load_manifest():
    path = Path(__file__).parent / "manifest.yaml"
    return yaml.safe_load(path.read_text())["checkpoints"]


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@pytest.fixture(params=_load_manifest(), ids=lambda c: c["name"])
def checkpoint_entry(request):
    return request.param


def test_checkpoint_loads_and_matches_reference(
    checkpoint_entry, checkpoint_dir, fixtures_dir, pytorch_dir,
):
    name = checkpoint_entry["name"]
    ckpt_path = checkpoint_dir / checkpoint_entry["filename"]
    if not ckpt_path.exists():
        pytest.skip(
            f"Checkpoint {ckpt_path} not present. Set LOCALVQE_CKPT_DIR or "
            f"download from Hugging Face to enable this test."
        )

    # SHA256 guards against accidentally testing a corrupt / wrong file.
    expected_sha = checkpoint_entry["sha256"]
    actual_sha = _sha256(ckpt_path)
    assert actual_sha == expected_sha, (
        f"{name} sha256 mismatch:\n  expected {expected_sha}\n  got      {actual_sha}"
    )

    cfg = yaml.safe_load((pytorch_dir / "configs" / "default.yaml").read_text())
    model_kwargs = dict(cfg["model"])
    model_kwargs["arch_version"] = checkpoint_entry["arch_version"]
    model = LocalVQE(**model_kwargs, n_freqs=cfg["audio"]["n_freqs"]).eval()

    blob = torch.load(ckpt_path, map_location="cpu", weights_only=True)
    sd_key = checkpoint_entry.get("state_dict_key")
    sd = blob[sd_key] if sd_key else blob
    model.load_state_dict(sd, strict=True)
    if checkpoint_entry.get("fold_temperature", False):
        model.align.fold_temperature()

    mic, ref = _deterministic_input()
    with torch.no_grad():
        y = model(mic, ref)

    ref_path = fixtures_dir / checkpoint_entry["reference_output"]
    if not ref_path.exists():
        pytest.fail(
            f"Missing reference output {ref_path}. Generate it with "
            f"`python tests/regenerate_fixtures.py {name}`."
        )
    expected = torch.load(ref_path, map_location="cpu", weights_only=True)

    assert y.shape == expected.shape, f"{name}: shape {y.shape} vs {expected.shape}"
    assert torch.isfinite(y).all(), f"{name}: forward produced non-finite values"
    # Tolerances chosen to absorb BLAS / PyTorch-version drift while
    # still catching anything that would change output by more than ~0.01%.
    assert torch.allclose(y, expected, atol=1e-5, rtol=1e-4), (
        f"{name}: output drift\n"
        f"  max abs diff: {(y - expected).abs().max().item():.3e}\n"
        f"  mean abs diff: {(y - expected).abs().mean().item():.3e}"
    )
