"""Forward-output snapshots for each `arch_version`, no checkpoint required.

These are checkpoint-free regression tests: build a model with a fixed
manual_seed, run forward on the deterministic input shared with the
GGML side, and compare against a committed snapshot tensor. They catch
silent numerical drift in either arch's forward path even on CI hosts
that don't have any published `.pt` available — and they're the only
numerical-drift test we have for `arch_version=1`, since no v1
PyTorch checkpoint was ever published.

Snapshots are regenerated by tests/regenerate_fixtures.py.
"""
from __future__ import annotations

from pathlib import Path

import pytest
import torch
import yaml

from localvqe.model import LocalVQE


# Pinned across both regenerate_fixtures.py and this test. Bumping
# either invalidates every snapshot in the fixtures dir.
_INIT_SEED = 1234
_INPUT_SEED = 20260510
_INPUT_LEN = 16000


def _deterministic_input():
    g = torch.Generator().manual_seed(_INPUT_SEED)
    mic = torch.randn(1, _INPUT_LEN, generator=g)
    ref = torch.randn(1, _INPUT_LEN, generator=g)
    return mic, ref


def _build_model(arch_version: int, pytorch_dir: Path) -> LocalVQE:
    cfg = yaml.safe_load((pytorch_dir / "configs" / "default.yaml").read_text())
    model_kwargs = dict(cfg["model"])
    model_kwargs["arch_version"] = arch_version
    torch.manual_seed(_INIT_SEED)
    return LocalVQE(**model_kwargs, n_freqs=cfg["audio"]["n_freqs"]).eval()


@pytest.mark.parametrize("arch_version", [1, 2])
def test_arch_forward_snapshot(arch_version, pytorch_dir, fixtures_dir):
    model = _build_model(arch_version, pytorch_dir)
    mic, ref = _deterministic_input()
    with torch.no_grad():
        y = model(mic, ref)

    snapshot_path = fixtures_dir / f"snapshot_arch{arch_version}.pt"
    if not snapshot_path.exists():
        pytest.fail(
            f"Missing snapshot {snapshot_path}. Generate it with "
            f"`python tests/regenerate_fixtures.py --arch-snapshots`."
        )
    expected = torch.load(snapshot_path, map_location="cpu", weights_only=True)

    assert y.shape == expected.shape
    assert torch.isfinite(y).all()
    assert torch.allclose(y, expected, atol=1e-5, rtol=1e-4), (
        f"arch_version={arch_version} forward output drifted from snapshot\n"
        f"  max abs diff: {(y - expected).abs().max().item():.3e}\n"
        f"  mean abs diff: {(y - expected).abs().mean().item():.3e}"
    )
